<#
.SYNOPSIS
    Injects or updates ## SDK sections in aidocs/reference/*.md files
    by parsing .NET and Java SDK source files.

.DESCRIPTION
    For each operationId (= md filename without extension):
      - Finds the matching async method in PublicApiClient.cs (IXxxClient interface)
      - Finds the matching primary method in SDK_JAVA/api/*.java
      - Builds a structured ## SDK Markdown section
      - Appends or replaces that section in the reference .md file
      - Only writes the file when content actually changes (idempotent)

.PARAMETER ReferenceDir
    Path to aidocs/reference containing *.md files. Default: .\aidocs\reference

.PARAMETER DotNetClientFile
    Path to PublicApiClient.cs. Default: .\SDK_NET\Autogenerated\PublicApiClient.cs
    Ignored when -DotNetXmlFile is provided.

.PARAMETER DotNetXmlFile
    Path to the NuGet XML documentation file (Rws.LanguageCloud.Sdk.xml).
    When this file exists it takes priority over -DotNetClientFile.
    Default: .\tools\Rws.LanguageCloud.Sdk.xml
    Obtain via: .\pipeline\Get-DotNetSdkXml.ps1
    (Invoke-AiDocsPipeline.ps1 downloads it automatically.)

.PARAMETER JavaApiDir
    Path to SDK_JAVA/api directory. Default: .\SDK_JAVA\api

.PARAMETER Operations
    Optional list of specific operationIds to process.
    If omitted, all reference files are processed.

.PARAMETER Force
    Re-write every file even when the SDK section content is unchanged.

.EXAMPLE
    .\pipeline\Update-SdkSections.ps1
    .\pipeline\Update-SdkSections.ps1 -Operations AcceptTask,GetProject
    .\pipeline\Update-SdkSections.ps1 -Force
#>
param(
    [string]   $ReferenceDir     = ".\aidocs\reference",
    [string]   $DotNetXmlFile    = ".\tools\Rws.LanguageCloud.Sdk.xml",
    [string]   $DotNetClientFile = ".\SDK_NET\Autogenerated\PublicApiClient.cs",
    [string]   $JavaApiDir       = ".\tools\java-api",
    [string[]] $Operations       = @(),
    [switch]   $Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ── Helpers ────────────────────────────────────────────────────────────────────

function ConvertTo-CamelCase ([string]$s) {
    if ([string]::IsNullOrEmpty($s)) { return $s }
    return $s[0].ToString().ToLower() + $s.Substring(1)
}

# Simplify .NET parameter list: strip CancellationToken, shorten System.* types
function Format-DotNetParams ([string]$raw) {
    $p = $raw
    # CancellationToken is always the last param and may include default(...)
    # Use [^,]* to capture through the closing ) of default(...)
    $p = $p -replace ',?\s*System\.Threading\.CancellationToken[^,]*', ''
    # Shorten generic collections
    $p = $p -replace 'System\.Collections\.Generic\.IEnumerable<([^>]+)>', 'IEnumerable<$1>'
    # Shorten nullable int/bool
    $p = $p -replace 'System\.Nullable<([^>]+)>', '$1?'
    return $p.Trim().TrimEnd(',').Trim()
}

# Split a parameter string on top-level commas
# Handles generics (IEnumerable<string>) and annotation parens (@Param("x"))
function Split-Params ([string]$params) {
    $result = [System.Collections.Generic.List[string]]::new()
    $depth   = 0
    $current = [System.Text.StringBuilder]::new()
    foreach ($c in $params.ToCharArray()) {
        if     ($c -eq '<' -or $c -eq '(') { $depth++ }
        elseif ($c -eq '>' -or $c -eq ')') { $depth-- }
        if ($c -eq ',' -and $depth -eq 0) {
            $trimmed = $current.ToString().Trim()
            if ($trimmed) { $result.Add($trimmed) }
            [void]$current.Clear()
        } else {
            [void]$current.Append($c)
        }
    }
    $last = $current.ToString().Trim()
    if ($last) { $result.Add($last) }
    return $result
}

# Build a markdown parameter table from a clean param list string
function Build-DotNetParamTable ([string]$params) {
    if ([string]::IsNullOrWhiteSpace($params)) { return "" }
    $rows  = Split-Params $params
    $lines = @("| Parameter | Type | Required |", "|---|---|---|")
    foreach ($row in $rows) {
        # Pattern: [type] [name] [= default]
        # e.g.: string taskId   |   int? top = null   |   IEnumerable<string> location = null
        if ($row -match '^(.+?)\s+(\w+)\s*(=.*)?$') {
            $type     = $matches[1].Trim()
            $name     = $matches[2].Trim()
            $hasDefault = ($matches[3] -and $matches[3].Trim())
            $required = if ($hasDefault) { "no" } else { "yes" }
            # Strip nullable ? for display
            $typeDisp = $type -replace '\?$', ''
            $lines += "| ``$name`` | ``$typeDisp`` | $required |"
        }
    }
    return $lines -join "`n"
}

# Build a markdown parameter table from Java raw params (with annotations)
function Build-JavaParamTable ([string]$rawParams) {
    if ([string]::IsNullOrWhiteSpace($rawParams)) { return "" }
    $rows  = Split-Params $rawParams
    $lines = @("| Parameter | Type | Required |", "|---|---|---|")
    foreach ($row in $rows) {
        # Determine required from Nonnull/Nullable BEFORE stripping
        $required = if ($row -match 'Nullable') { "no" } else { "yes" }
        # Strip all annotations: @Param("x"), @javax.annotation.Nonnull/Nullable, @Nonnull, @Nullable
        $clean = $row -replace '@javax\.annotation\.\w+\s*', ''
        $clean = $clean -replace '@\w+(\("[^"]*"\))?\s*', ''
        $clean = $clean.Trim()
        # Now: "Type name"
        if ($clean -match '^(.+?)\s+(\w+)$') {
            $type = $matches[1].Trim() -replace '^java\.lang\.', ''
            $name = $matches[2].Trim()
            $lines += "| ``$name`` | ``$type`` | $required |"
        }
    }
    return $lines -join "`n"
}

# ── Parse .NET SDK from NuGet XML documentation ──────────────────────────────

# Split a comma-separated type list from a .NET XML member name signature.
# Uses {} depth counting to handle generic type args  e.g. Nullable{Int32}
function Split-XmlTypeList ([string]$typeStr) {
    $result  = [System.Collections.Generic.List[string]]::new()
    $depth   = 0
    $current = [System.Text.StringBuilder]::new()
    foreach ($c in $typeStr.ToCharArray()) {
        if     ($c -eq '{') { $depth++ }
        elseif ($c -eq '}') { $depth-- }
        if ($c -eq ',' -and $depth -eq 0) {
            $t = $current.ToString().Trim()
            if ($t) { $result.Add($t) }
            [void]$current.Clear()
        } else {
            [void]$current.Append($c)
        }
    }
    $t = $current.ToString().Trim()
    if ($t) { $result.Add($t) }
    return $result
}

# Shorten a fully-qualified .NET type string from XML member-name format.
# XML uses {} for generic brackets:  System.Nullable{System.Int32}
function Shorten-DotNetXmlType ([string]$fqType) {
    $fqType = $fqType.Trim()

    # Nullable<T>  →  T?
    if ($fqType -match '^System\.Nullable\{(.+)\}$') {
        return (Shorten-DotNetXmlType $matches[1]) + '?'
    }

    # Generic outer type  (e.g. IEnumerable{T}, List{T})
    if ($fqType -match '^.+\.([A-Z]\w+)\{(.+)\}$') {
        $baseName   = $matches[1]
        $innerShort = Shorten-DotNetXmlType $matches[2]
        return "$baseName<$innerShort>"
    }

    # Primitive type aliases
    switch ($fqType) {
        'System.String'  { return 'string' }
        'System.Int32'   { return 'int'    }
        'System.Int64'   { return 'long'   }
        'System.Boolean' { return 'bool'   }
        'System.Double'  { return 'double' }
        'System.Single'  { return 'float'  }
        'System.Decimal' { return 'decimal'}
        'System.Object'  { return 'object' }
        'System.Void'    { return 'void'   }
        'System.Byte'    { return 'byte'   }
    }

    # Strip namespace: take last dotted segment
    $lastDot = $fqType.LastIndexOf('.')
    if ($lastDot -ge 0) { return $fqType.Substring($lastDot + 1) }
    return $fqType
}

# Infer the C# return type for a method from its operation name and <returns> text.
# The XML member-name format does NOT include the return type, so we use heuristics.
function Get-DotNetReturnTypeHeuristic ([string]$opId, [string]$returnsText) {
    # Explicit void
    if ($returnsText -match 'No Content') { return 'Task' }

    # Void by operation-name convention
    $voidPrefixes = 'Delete|Accept|Reject|Release|Reclaim|Assign|Cancel|Reschedule|' +
                    'AddProjectsToGroup|RemoveProjectsFromGroup|CompleteTask|CompleteProject|' +
                    'StartTask|UpdateTranslationEngine|UpdateWorkflow|UpdateProjectConfiguration'
    if ($opId -match "^($voidPrefixes)") { return 'Task' }

    # List* → Task<List*Response>
    if ($opId -match '^List(.+)$') { return "Task<List$($matches[1])Response>" }

    # Get* / Create* / Copy* → Task<ResourceType>
    if ($opId -match '^Get(.+)$')    { return "Task<$($matches[1])>" }
    if ($opId -match '^Create(.+)$') { return "Task<$($matches[1])>" }
    if ($opId -match '^Copy(.+)$')   { return "Task<$($matches[1])>" }

    # Everything else (Download, Export, Poll, Import, Update, Add…) defaults to Task
    return 'Task'
}

# Parse the NuGet XML documentation file into an operation-id → method map.
# Targets interface members (I*Client) only.
function Get-DotNetMethodMapFromXml ([string]$xmlPath) {
    Write-Host "  Parsing .NET SDK from NuGet XML..." -NoNewline
    [xml]$doc = Get-Content $xmlPath -Raw
    $map = @{}

    # Optional param names that are typically nullable / defaulted to null in the SDK
    $knownOptional = @('fields','top','skip','sort','filter','onBehalfOfGroup',
                       'locationStrategy','createdFrom','createdTo','createdBy',
                       'name','status','assigneeId','type')

    foreach ($member in $doc.doc.members.member) {
        $memberName = $member.name

        # Match interface method members:  M:...IXxxClient.MethodAsync(
        if ($memberName -notmatch '^M:[\w.]+\.(I\w+Client)\.(\w+Async)\(') { continue }

        $ifaceName   = $matches[1]   # e.g. ITaskClient
        $methodName  = $matches[2]   # e.g. AcceptTaskAsync
        $operationId = $methodName -replace 'Async$', ''

        # Extract the comma-separated type list between the first ( and last )
        $parenStart = $memberName.IndexOf('(')
        $typeStr    = if ($parenStart -ge 0) { $memberName.Substring($parenStart + 1).TrimEnd(')') } else { '' }
        $allTypes   = if ($typeStr) { @(Split-XmlTypeList $typeStr) } else { @() }

        # Remove CancellationToken — it is always present but never shown
        $paramTypes = @($allTypes | Where-Object { $_ -notmatch 'CancellationToken' })

        # Get parameter names from <param> elements.
        # NSwag consistently places the cancellationToken <param> FIRST in the XML
        # doc comment, followed by the real parameters in declaration order.
        $allParamEls = $member.SelectNodes('param')
        $paramNames  = @($allParamEls |
                         Where-Object { $_.name -ne 'cancellationToken' } |
                         ForEach-Object { $_.name })

        # Shorten each type
        $shortTypes = @($paramTypes | ForEach-Object { Shorten-DotNetXmlType $_ })

        # Zip names and types; encode optional params with = null so the existing
        # Build-DotNetParamTable function correctly marks them as not required
        $count = [Math]::Min($paramNames.Count, $shortTypes.Count)
        $parts = for ($i = 0; $i -lt $count; $i++) {
            $sType = $shortTypes[$i]
            $pName = $paramNames[$i]
            $isOpt = $sType.EndsWith('?') -or ($pName -in $knownOptional)
            if ($isOpt) { "$sType $pName = null" } else { "$sType $pName" }
        }
        $cleanParams = $parts -join ', '

        # Return type via heuristic (not available in XML member name)
        $returnsNode = $member.SelectSingleNode('returns')
        $returnsText = if ($returnsNode) { $returnsNode.InnerText } else { '' }
        $retType     = Get-DotNetReturnTypeHeuristic $operationId $returnsText

        $sig = if ($retType -eq 'Task') { "Task ${methodName}($cleanParams)" }
               else                     { "$retType ${methodName}($cleanParams)" }

        # First match wins (interface docs may appear before implementation docs)
        if (-not $map.ContainsKey($operationId)) {
            $summaryNode = $member.SelectSingleNode('summary')
            $map[$operationId] = [PSCustomObject]@{
                Interface  = $ifaceName
                Summary    = if ($summaryNode) { $summaryNode.InnerText.Trim() } else { '' }
                MethodName = $methodName
                ReturnType = $retType
                Parameters = $cleanParams
                Signature  = $sig
            }
        }
    }

    Write-Host " found $($map.Count) methods."
    return $map
}

# Clean Java raw params for display in code block (strip annotations, keep type+name)
function Format-JavaParams ([string]$rawParams) {
    if ([string]::IsNullOrWhiteSpace($rawParams)) { return "" }
    $parts = Split-Params $rawParams
    $clean = $parts | ForEach-Object {
        $p = $_ -replace '@javax\.annotation\.\w+\s*', ''
        $p = $p -replace '@\w+(\("[^"]*"\))?\s*', ''
        $p.Trim()
    }
    return ($clean | Where-Object { $_ }) -join ', '
}

# ── Parse .NET SDK ─────────────────────────────────────────────────────────────

function Get-DotNetMethodMap ([string]$filePath) {
    Write-Host "  Parsing .NET SDK..." -NoNewline
    $map            = @{}
    $lines          = [System.IO.File]::ReadAllLines($filePath)
    $currentIface   = $null
    $braceDepth     = 0
    $inIface        = $false
    $seenOpenBrace  = $false
    $lastSummary    = $null

    for ($i = 0; $i -lt $lines.Length; $i++) {
        $line = $lines[$i]

        # Detect interface start: matches 'public interface' and 'public partial interface'
        if ($line -match '^\s*public (?:partial )?interface (I\w+)') {
            $currentIface  = $matches[1]
            $inIface       = $true
            $braceDepth    = 0
            $seenOpenBrace = $false
        }

        if ($inIface) {
            # Capture summary and method BEFORE updating brace depth so we
            # process the closing-brace line correctly (depth goes to 0 after method check)

            # Capture inline summary: /// <summary>text</summary>
            if ($line -match '///\s*<summary>(.+?)</summary>') {
                $lastSummary = $matches[1].Trim()
            }

            # Interface method declaration (ends with semicolon, not opening brace)
            # System.Threading.Tasks.Task<ReturnType> MethodNameAsync(params);
            if ($currentIface -and
                $line -match '^\s*System\.Threading\.Tasks\.Task(?:<([^>]+)>)?\s+(\w+Async)\((.+)\)\s*;') {

                $retType     = if ($matches[1]) { $matches[1].Trim() } else { 'void' }
                $methodName  = $matches[2]
                $rawParams   = $matches[3]
                $operationId = $methodName -replace 'Async$', ''
                $cleanParams = Format-DotNetParams $rawParams

                # Produce the clean signature for display (no System.Threading prefixes)
                $retDisp = $retType -replace '^System\.Threading\.Tasks\.', ''
                $sig     = if ($retType -eq 'void') { "Task $methodName($cleanParams)" } `
                           else { "Task<$retDisp> $methodName($cleanParams)" }

                if (-not $map.ContainsKey($operationId)) {
                    $map[$operationId] = [PSCustomObject]@{
                        Interface    = $currentIface
                        Summary      = $lastSummary
                        MethodName   = $methodName
                        ReturnType   = $retType
                        Parameters   = $cleanParams
                        Signature    = $sig
                    }
                }
                $lastSummary = $null
            }

            # Update brace depth AFTER method detection
            foreach ($c in $line.ToCharArray()) {
                if ($c -eq '{') { $braceDepth++; $seenOpenBrace = $true }
                elseif ($c -eq '}') { $braceDepth-- }
            }
            # Only end interface AFTER the opening brace has been seen
            if ($seenOpenBrace -and $braceDepth -le 0) {
                $inIface       = $false
                $currentIface  = $null
                $braceDepth    = 0
                $seenOpenBrace = $false
            }
        }
    }

    Write-Host " found $($map.Count) methods."
    return $map
}

# ── Parse Java SDK ─────────────────────────────────────────────────────────────

function Get-JavaMethodMap ([string]$apiDir) {
    Write-Host "  Parsing Java SDK..." -NoNewline
    $map = @{}

    foreach ($javaFile in Get-ChildItem $apiDir -Filter "*Api.java") {
        $apiClass = $javaFile.BaseName          # e.g. TaskApi
        $lines    = [System.IO.File]::ReadAllLines($javaFile.FullName)
        # States: idle → gotRequestLine → collectingAnnotations → done
        $requestLine     = $null
        $skipUntilSemi   = $false
        $inHeadersBlock  = $false

        for ($i = 0; $i -lt $lines.Length; $i++) {
            $line = $lines[$i]

            # Skip multi-line @Headers({...}) blocks
            if ($inHeadersBlock) {
                if ($line -match '\}') { $inHeadersBlock = $false }
                continue
            }

            # Capture @RequestLine
            if ($line -match '@RequestLine\("(\w+)\s+([^"]+)"\)') {
                $requestLine = "$($matches[1]) $($matches[2])"
                continue
            }

            # Start of @Headers block
            if ($requestLine -and $line -match '@Headers\(\{') {
                if ($line -notmatch '\}') { $inHeadersBlock = $true }
                continue
            }

            # Skip other annotations between @RequestLine and method
            if ($requestLine -and $line -match '^\s*@') {
                continue
            }

            if ($requestLine) {
                # Method declaration line: returnType methodName(params);
                # Use greedy (.+) so annotations like @Param("x") with nested parens are captured
                if ($line -match '^\s+(void|ApiResponse<[\w,\s<>]+>|[\w<>\[\]]+)\s+(\w+)\s*\((.+)\)\s*;') {
                    $retType    = $matches[1].Trim()
                    $methodName = $matches[2].Trim()
                    $rawParams  = $matches[3].Trim()

                    # Only take primary methods — skip *WithHttpInfo and *QueryMap variants
                    if ($methodName -notmatch 'WithHttpInfo$' -and
                        $rawParams -notmatch '@QueryMap') {

                        $operationId = $methodName[0].ToString().ToUpper() + $methodName.Substring(1)
                        $cleanParams = Format-JavaParams $rawParams

                        if (-not $map.ContainsKey($operationId)) {
                            $map[$operationId] = [PSCustomObject]@{
                                ApiClass    = $apiClass
                                MethodName  = $methodName
                                ReturnType  = $retType
                                RawParams   = $rawParams
                                Parameters  = $cleanParams
                                RequestLine = $requestLine
                                Signature   = "$retType $methodName($cleanParams)"
                            }
                        }
                    }
                    $requestLine = $null
                } elseif ($line.Trim() -and $line -notmatch '^\s*//' -and $line -notmatch '^\s*@') {
                    # Unexpected non-annotation non-comment line: reset state
                    $requestLine = $null
                }
            }
        }
    }

    Write-Host " found $($map.Count) methods."
    return $map
}

# ── Build ## SDK section ───────────────────────────────────────────────────────

function Build-SdkSection ([string]$operationId, $dotNet, $java) {
    $sb = [System.Text.StringBuilder]::new()

    [void]$sb.AppendLine("## SDK")

    # ── .NET ──────────────────────────────────────────────────────────────────
    [void]$sb.AppendLine()
    if ($dotNet) {
        [void]$sb.AppendLine("### .NET — ``$($dotNet.Interface)``")
        [void]$sb.AppendLine()
        [void]$sb.AppendLine('```csharp')
        [void]$sb.AppendLine($dotNet.Signature + ";")
        [void]$sb.AppendLine('```')
        $table = Build-DotNetParamTable $dotNet.Parameters
        if ($table) {
            [void]$sb.AppendLine()
            [void]$sb.AppendLine($table)
        }
    } else {
        [void]$sb.AppendLine("### .NET")
        [void]$sb.AppendLine()
        [void]$sb.AppendLine("_Not found in .NET SDK — [Manual Review Needed]_")
    }

    # ── Java ──────────────────────────────────────────────────────────────────
    [void]$sb.AppendLine()
    if ($java) {
        [void]$sb.AppendLine("### Java — ``$($java.ApiClass)``")
        [void]$sb.AppendLine()
        [void]$sb.AppendLine('```java')
        [void]$sb.AppendLine("// $($java.RequestLine)")
        [void]$sb.AppendLine($java.Signature + ";")
        [void]$sb.AppendLine('```')
        $table = Build-JavaParamTable $java.RawParams
        if ($table) {
            [void]$sb.AppendLine()
            [void]$sb.AppendLine($table)
        }
    } else {
        [void]$sb.AppendLine("### Java")
        [void]$sb.AppendLine()
        [void]$sb.AppendLine("_Not found in Java SDK — [Manual Review Needed]_")
    }

    return $sb.ToString().TrimEnd()
}

# ── Write reference file ───────────────────────────────────────────────────────

function Update-ReferenceFile ([string]$filePath, [string]$sdkSection) {
    $content = [System.IO.File]::ReadAllText($filePath)
    $marker  = "`n## SDK"
    $idx     = $content.IndexOf($marker)

    if ($idx -ge 0) {
        $existing = $content.Substring($idx).TrimStart()
        if (-not $Force -and $existing.Trim() -eq $sdkSection.Trim()) {
            return $false   # no change
        }
        $newContent = $content.Substring(0, $idx).TrimEnd() + "`n`n" + $sdkSection
    } else {
        $newContent = $content.TrimEnd() + "`n`n" + $sdkSection
    }

    [System.IO.File]::WriteAllText($filePath, $newContent, [System.Text.Encoding]::UTF8)
    return $true
}

# ── Main ───────────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "=== Update-SdkSections ===" -ForegroundColor Cyan
Write-Host "Reference dir  : $ReferenceDir"
if ($DotNetXmlFile) {
    Write-Host ".NET SDK (XML) : $DotNetXmlFile"
} else {
    Write-Host ".NET SDK (src) : $DotNetClientFile"
}
Write-Host "Java SDK dir   : $JavaApiDir"
if ($Operations.Count -gt 0) { Write-Host "Operations     : $($Operations -join ', ')" }
if ($Force) { Write-Host "Mode           : FORCE (rewrite all)" -ForegroundColor Yellow }
Write-Host ""

if ($DotNetXmlFile -and (Test-Path $DotNetXmlFile)) {
    $dotNetMap = Get-DotNetMethodMapFromXml $DotNetXmlFile
} elseif (Test-Path $DotNetClientFile) {
    $dotNetMap = Get-DotNetMethodMap $DotNetClientFile
} else {
    Write-Warning "No .NET SDK source found. Checked:\n  XML : $DotNetXmlFile\n  CS  : $DotNetClientFile\nRun: .\pipeline\Get-DotNetSdkXml.ps1"
    $dotNetMap = @{}
}
$javaMap = Get-JavaMethodMap $JavaApiDir
Write-Host ""

$exclude = @("Index.md", "Schemas.md", "components.md")
$mdFiles = Get-ChildItem $ReferenceDir -Filter "*.md" |
           Where-Object { $_.Name -notin $exclude } |
           Sort-Object Name

if ($Operations.Count -gt 0) {
    $mdFiles = $mdFiles | Where-Object { $Operations -contains $_.BaseName }
    Write-Host "Targeting $($mdFiles.Count) specified operation(s)"
} else {
    Write-Host "Processing $($mdFiles.Count) reference files"
}
Write-Host ""

$updated = 0; $unchanged = 0; $noSdk = 0

foreach ($file in $mdFiles) {
    $opId   = $file.BaseName
    $dotNet = $dotNetMap[$opId]
    $java   = $javaMap[$opId]

    if (-not $dotNet -and -not $java) {
        Write-Warning "  No SDK data: $opId"
        $noSdk++
        continue
    }

    $section = Build-SdkSection $opId $dotNet $java
    $wrote   = Update-ReferenceFile $file.FullName $section

    if ($wrote) {
        Write-Host "  [updated ] $opId" -ForegroundColor Green
        $updated++
    } else {
        $unchanged++
    }
}

Write-Host ""
Write-Host "Done. Updated: $updated  Unchanged: $unchanged  No SDK data: $noSdk" -ForegroundColor Cyan
